name = "human-in-the-loop"
main = "./src/server.ts"
compatibility_date = "2026-01-28"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "public" }

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "HumanInTheLoop"
class_name = "HumanInTheLoop"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["HumanInTheLoop"]
